### ISSUE TITLE
SOAK Testing: Disable flux sync to prevent cron jobs from running during load testing

### ISSUE THREAD

**Issue by PurpleBriar** [retaildevcrews/loderunner#214]
## Description

What: 
 - Disable flux sync to prevent cron jobs from running during load testing
 
Why:
- To support LR SOAK test 

When:
- After code freeze

Where:
 - Dev cluster, region WestUS2

## Constraints
- N/A 

## References:
- References [#340](https://github.com/retaildevcrews/wcnp/issues/340)

**Comment by joaquinrz** [comment]
Flux was disabled before soak test, and re-enabled when done
