### ISSUE TITLE
Failing AutoGitOps workflow

### ISSUE THREAD

**Issue by rcaseymsft** [retaildevcrews/loderunner#310]
What: 
- Scheduled AutoGitOps workflow deploy fails because pushing updates to protected branch ngsa-asb (main) is not allowed
 
Why:
- Ensure automated workflows do not fail

When:
- On run of scheduled AutoGitOps workflow

Where:
- Loderunner repository GitHub actions

## Tasks
- [x] Reenable write access in ngsa-asb
- [x] Rerun job for successful completion

## Acceptance Criteria

- AutoGitOps workflow is completing successfully

## References:

**Comment by mbernstine** [comment]
This was caused by an attempted configuration to address #1039. Configuration was rolled back so this is no longer an issue.
